-- ============================================================================
-- PART 1: TABLE ALTERATIONS (Run this first)
-- ============================================================================

-- CHANGE ORDERS TABLE
ALTER TABLE change_orders
ADD COLUMN IF NOT EXISTS co_number INTEGER,
ADD COLUMN IF NOT EXISTS co_type VARCHAR(30),
ADD COLUMN IF NOT EXISTS date DATE,
ADD COLUMN IF NOT EXISTS sent_date DATE,
ADD COLUMN IF NOT EXISTS notes TEXT;

-- CHANGE ORDER ITEMS TABLE
ALTER TABLE change_order_items
ADD COLUMN IF NOT EXISTS price NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

-- LONG LEAD ITEMS TABLE
ALTER TABLE long_lead_items
ADD COLUMN IF NOT EXISTS quantity INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS has_cutsheet BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS cutsheet_url TEXT,
ADD COLUMN IF NOT EXISTS cutsheet_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS submitted_date DATE,
ADD COLUMN IF NOT EXISTS signoff_date DATE;

-- COLOR SELECTIONS TABLE
ALTER TABLE color_selections
ADD COLUMN IF NOT EXISTS item_name VARCHAR(200),
ADD COLUMN IF NOT EXISTS cutsheet_url TEXT,
ADD COLUMN IF NOT EXISTS cutsheet_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS is_non_stock BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS non_stock_verified BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS non_stock_lead_time VARCHAR(50);

-- WARNING EMAILS LOG TABLE
ALTER TABLE warning_emails_log
ADD COLUMN IF NOT EXISTS sent_to_emails TEXT[],
ADD COLUMN IF NOT EXISTS email_subject VARCHAR(255),
ADD COLUMN IF NOT EXISTS email_body TEXT,
ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'Sent';

-- PROJECTS TABLE
ALTER TABLE projects
ADD COLUMN IF NOT EXISTS health_status VARCHAR(30) DEFAULT 'On Track';
